=== henesy/cs363/proj3/UniversityOODB.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2015 sp2 (x64) (http://www.altova.com) by Ying Wei (Iowa State University) -->
<!-- edited with XMLSPY v5 rel. 3 U (http://www.xmlspy.com) by Shihe Ma (Iowa State University, Computer Science) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="University">
		<xs:annotation>
			<xs:documentation>University Object-Oriented Scheme</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Person" type="PersonType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="Faculty" type="FacultyType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="Student" type="StudentType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="Course" type="CourseType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="Offering" type="OfferingType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="Enrollment" type="EnrollmentType" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="PersonType">
		<xs:sequence>
			<xs:element name="Name" type="xs:string"/>
			<xs:element name="Address" type="xs:string"/>
			<xs:element name="DOB" type="xs:date"/>
		</xs:sequence>
		<xs:attribute name="PersonID" type="xs:ID" use="required"/>
	</xs:complexType>
	<xs:complexType name="FacultyType">
		<xs:sequence>
			<xs:element name="ISA">
				<xs:complexType>
					<xs:attribute name="oType" type="xs:string" use="required" fixed="PersonType"/>
					<xs:attribute name="oID" type="xs:IDREF" use="required"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="Salary" type="xs:int"/>
			<xs:element name="Rank" type="xs:string"/>
			<xs:element name="Mentoring">
				<xs:complexType>
					<xs:attribute name="oType" type="xs:string" use="required" fixed="StudentType"/>
					<xs:attribute name="oID" type="xs:IDREFS" use="required"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="Instructing">
				<xs:complexType>
					<xs:attribute name="oType" type="xs:string" use="required" fixed="OfferingType"/>
					<xs:attribute name="oID" type="xs:IDREFS" use="required"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="FacultyID" type="xs:ID" use="required"/>
	</xs:complexType>
	<xs:complexType name="StudentType">
		<xs:sequence>
			<xs:element name="ISA">
				<xs:complexType>
					<xs:attribute name="oType" type="xs:string" use="required" fixed="PersonType"/>
					<xs:attribute name="oID" type="xs:IDREF" use="required"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="Classification" type="xs:string"/>
			<xs:element name="CreditHours" type="xs:int"/>
			<xs:element name="GPA" type="xs:decimal"/>
			<xs:element name="Mentor">
				<xs:complexType>
					<xs:attribute name="oType" type="xs:string" use="required" fixed="FacultyType"/>
					<xs:attribute name="oID" type="xs:IDREF" use="required"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="EnrolledIn">
				<xs:complexType>
					<xs:attribute name="oType" type="xs:string" use="required" fixed="EnrollmentType"/>
					<xs:attribute name="oID" type="xs:IDREFS" use="required"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="StudentID" type="xs:ID" use="required"/>
	</xs:complexType>
	<xs:complexType name="CourseType">
		<xs:sequence>
			<xs:element name="CourseCode" type="xs:string"/>
			<xs:element name="CourseName" type="xs:string"/>
			<xs:element name="PreReqs">
				<xs:annotation>
					<xs:documentation>Reference to Course</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:attribute name="oType" type="xs:string" use="required" fixed="CourseType"/>
					<xs:attribute name="oID" type="xs:IDREFS" use="required"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="OfferedAs">
				<xs:complexType>
					<xs:attribute name="oType" type="xs:normalizedString" use="required" fixed="OfferingType"/>
					<xs:attribute name="oID" type="xs:IDREFS" use="required"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="CourseID" type="xs:ID" use="required"/>
	</xs:complexType>
	<xs:complexType name="OfferingType">
		<xs:sequence>
			<xs:element name="CourseInfo">
				<xs:complexType>
					<xs:attribute name="oType" type="xs:string" use="required" fixed="CourseType"/>
					<xs:attribute name="oID" type="xs:IDREF" use="required"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="Section" type="xs:int"/>
			<xs:element name="Instructor">
				<xs:complexType>
					<xs:attribute name="oType" type="xs:string" use="required" fixed="FacultyType"/>
					<xs:attribute name="oID" type="xs:IDREF" use="required"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="Enrollments">
				<xs:complexType>
					<xs:attribute name="oType" type="xs:string" use="required" fixed="EnrollmentType"/>
					<xs:attribute name="oID" type="xs:IDREFS" use="required"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="OfferingID" type="xs:ID" use="required"/>
	</xs:complexType>
	<xs:complexType name="EnrollmentType">
		<xs:sequence>
			<xs:element name="OfferingInfo">
				<xs:complexType>
					<xs:attribute name="oType" type="xs:string" use="required" fixed="OfferingType"/>
					<xs:attribute name="oID" type="xs:IDREF" use="required"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="StudentInfo">
				<xs:complexType>
					<xs:attribute name="oType" type="xs:string" use="required" fixed="StudentType"/>
					<xs:attribute name="oID" type="xs:IDREF" use="required"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="Grade" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="EnrollmentID" type="xs:ID" use="required"/>
	</xs:complexType>
</xs:schema>

=== henesy/cs363/proj3/CyDIW_Root/ComS363/Projects/Datasets Spring 2015/UniversityOODB.xml
<?xml version="1.0" encoding="UTF-8"?>
<University xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="UniversityOODB.xsd">
	<Person PersonID="p115423723">
		<Name>Wee Fletcher</Name>
		<Address>1234 Hayward Avenue</Address>
		<DOB>1974-09-23</DOB>
	</Person>
	<Person PersonID="p118784412">
		<Name>Jinchao Henson</Name>
		<Address>236 Westland Street</Address>
		<DOB>1976-07-24</DOB>
	</Person>
	<Person PersonID="p120308944">
		<Name>Gene Lehmer</Name>
		<Address>746 Creekside</Address>
		<DOB>1974-12-06</DOB>
	</Person>
	<Person PersonID="p124208644">
		<Name>John Basaraba</Name>
		<Address>678 Westside Apartments</Address>
		<DOB>1974-06-07</DOB>
	</Person>
	<Person PersonID="p126544126">
		<Name>Jason Wang</Name>
		<Address>876 Westburrow</Address>
		<DOB>1977-09-15</DOB>
	</Person>
	<Person PersonID="p131838016">
		<Name>Daniel Woo</Name>
		<Address>890 3rd Street</Address>
		<DOB>1976-03-12</DOB>
	</Person>
	<Person PersonID="p143293833">
		<Name>Jamie Yang</Name>
		<Address>365 Ash Avenue</Address>
		<DOB>1972-02-08</DOB>
	</Person>
	<Person PersonID="p163728111">
		<Name>Todd Lu</Name>
		<Address>89 Williamstown</Address>
		<DOB>1977-12-12</DOB>
	</Person>
	<Person PersonID="p164500920">
		<Name>Omar Shahnawaz</Name>
		<Address>8234 9th Street</Address>
		<DOB>1975-08-28</DOB>
	</Person>
	<Person PersonID="p164776911">
		<Name>Jason Huang</Name>
		<Address>8900 Wilhelm Drive</Address>
		<DOB>1976-09-30</DOB>
	</Person>
	<Person PersonID="p170815037">
		<Name>Yeow Huang</Name>
		<Address>3456 Osborn Drive</Address>
		<DOB>1975-11-23</DOB>
	</Person>
	<Person PersonID="p185141262">
		<Name>William Stumpf</Name>
		<Address>6389 Stange Avenue</Address>
		<DOB>1973-05-23</DOB>
	</Person>
	<Person PersonID="p191083779">
		<Name>Sameer Shah</Name>
		<Address>30 West Street</Address>
		<DOB>1978-09-15</DOB>
	</Person>
	<Person PersonID="p201586985">
		<Name>Min Tuyet</Name>
		<Address>378 Northridge</Address>
		<DOB>1976-12-03</DOB>
	</Person>
	<Person PersonID="p203745018">
		<Name>Brian Stumpf</Name>
		<Address>6780 Leword Avenue</Address>
		<DOB>1976-09-01</DOB>
	</Person>
	<Person PersonID="p212976207">
		<Name>Jason Newman</Name>
		<Address>786 Johnson Avenue</Address>
		<DOB>1974-09-28</DOB>
	</Person>
	<Person PersonID="p221157745">
		<Name>Adam Lee</Name>
		<Address>234 Lincoln Way</Address>
		<DOB>1976-01-09</DOB>
	</Person>
	<Person PersonID="p222105935">
		<Name>Wee Wang</Name>
		<Address>368 Kennedy Blvd</Address>
		<DOB>1978-01-12</DOB>
	</Person>
	<Person PersonID="p224620876">
		<Name>Feng Huang</Name>
		<Address>824 South Blvd</Address>
		<DOB>1975-01-23</DOB>
	</Person>
	<Person PersonID="p232820149">
		<Name>Lin Zhou</Name>
		<Address>678 Prince Blvd</Address>
		<DOB>1976-11-30</DOB>
	</Person>
	<Person PersonID="p252533260">
		<Name>Eric Wang</Name>
		<Address>3478 South 18th Street</Address>
		<DOB>1975-04-14</DOB>
	</Person>
	<Person PersonID="p259028125">
		<Name>Aaron Newman</Name>
		<Address>456 Stanton Drive</Address>
		<DOB>1976-03-14</DOB>
	</Person>
	<Person PersonID="p260369148">
		<Name>Yanqiu Huang</Name>
		<Address>780 Westpark</Address>
		<DOB>1973-11-19</DOB>
	</Person>
	<Person PersonID="p261812056">
		<Name>Jason Carney</Name>
		<Address>864 9th Street</Address>
		<DOB>1974-09-30</DOB>
	</Person>
	<Person PersonID="p262891588">
		<Name>Randy Hellman</Name>
		<Address>7832 Knapp Street</Address>
		<DOB>1973-09-13</DOB>
	</Person>
	<Person PersonID="p271978135">
		<Name>Wen White</Name>
		<Address>834 West Street</Address>
		<DOB>1976-04-11</DOB>
	</Person>
	<Person PersonID="p273277984">
		<Name>Lee Andrews</Name>
		<Address>786 Burlington</Address>
		<DOB>1976-05-13</DOB>
	</Person>
	<Person PersonID="p279702622">
		<Name>Zhen Messer</Name>
		<Address>246 Creekside</Address>
		<DOB>1974-03-13</DOB>
	</Person>
	<Person PersonID="p285719425">
		<Name>Chee Yang</Name>
		<Address>9602 Manhattan</Address>
		<DOB>1977-03-04</DOB>
	</Person>
	<Person PersonID="p290986112">
		<Name>Golam Bagga</Name>
		<Address>468 Northridge</Address>
		<DOB>1973-12-03</DOB>
	</Person>
	<Person PersonID="p296669559">
		<Name>Wee Tuyet</Name>
		<Address>2300 Westside Park</Address>
		<DOB>1976-06-01</DOB>
	</Person>
	<Person PersonID="p302335678">
		<Name>Eric Dennis</Name>
		<Address>2345 Sterling Apartments</Address>
		<DOB>1975-11-12</DOB>
	</Person>
	<Person PersonID="p308635036">
		<Name>Scot Lee</Name>
		<Address>3800 Bloomington</Address>
		<DOB>1976-02-14</DOB>
	</Person>
	<Person PersonID="p315967897">
		<Name>Jialiang Jiang</Name>
		<Address>4563 South Street</Address>
		<DOB>1974-03-16</DOB>
	</Person>
	<Person PersonID="p328718420">
		<Name>Colleen Parcher</Name>
		<Address>9046 Burlington</Address>
		<DOB>1977-04-05</DOB>
	</Person>
	<Person PersonID="p330260152">
		<Name>Ling Tesar</Name>
		<Address>4678 West Street</Address>
		<DOB>1978-05-06</DOB>
	</Person>
	<Person PersonID="p332012037">
		<Name>Randy Lewis</Name>
		<Address>34 Wilhelm Drive</Address>
		<DOB>1972-06-07</DOB>
	</Person>
	<Person PersonID="p340502961">
		<Name>Josh Woo</Name>
		<Address>1002 Creekside</Address>
		<DOB>1973-07-08</DOB>
	</Person>
	<Person PersonID="p363200537">
		<Name>Wee Whitteney</Name>
		<Address>1004 Northridge</Address>
		<DOB>1974-08-09</DOB>
	</Person>
	<Person PersonID="p365774792">
		<Name>William Yang</Name>
		<Address>1800 13th Street</Address>
		<DOB>1975-09-10</DOB>
	</Person>
	<Person PersonID="p382109560">
		<Name>Dennis Fletcher</Name>
		<Address>225 North Hyland</Address>
		<DOB>1976-10-11</DOB>
	</Person>
	<Person PersonID="p386167477">
		<Name>Seth Carney</Name>
		<Address>346 Ash Drive</Address>
		<DOB>1977-11-12</DOB>
	</Person>
	<Person PersonID="p387215322">
		<Name>Colleen Good</Name>
		<Address>356 Chamberlain Street</Address>
		<DOB>1978-12-13</DOB>
	</Person>
	<Person PersonID="p391910519">
		<Name>Ming Jiang</Name>
		<Address>24 Main Street</Address>
		<DOB>1972-01-14</DOB>
	</Person>
	<Person PersonID="p406746417">
		<Name>Ryan Schmidt</Name>
		<Address>240 East Lincoln Way</Address>
		<DOB>1973-02-15</DOB>
	</Person>
	<Person PersonID="p409508678">
		<Name>Golam Mohammad</Name>
		<Address>2040 6th Street</Address>
		<DOB>1974-03-16</DOB>
	</Person>
	<Person PersonID="p419180204">
		<Name>Kerry Marks</Name>
		<Address>2400 West Street</Address>
		<DOB>1975-04-17</DOB>
	</Person>
	<Person PersonID="p432180765">
		<Name>Eric Loader</Name>
		<Address>268 Burlington</Address>
		<DOB>1976-05-18</DOB>
	</Person>
	<Person PersonID="p449976666">
		<Name>Jun Wang</Name>
		<Address>1006 Lebert Hall</Address>
		<DOB>1956-09-15</DOB>
	</Person>
	<Person PersonID="p463249547">
		<Name>Chad Moore</Name>
		<Address>245 Stange Avenue</Address>
		<DOB>1977-06-19</DOB>
	</Person>
	<Person PersonID="p466094162">
		<Name>Stumpf Andrews</Name>
		<Address>3400 28th Street</Address>
		<DOB>1978-07-20</DOB>
	</Person>
	<Person PersonID="p466388906">
		<Name>Darren Lehmann</Name>
		<Address>348 Duff Avenue</Address>
		<DOB>1972-08-21</DOB>
	</Person>
	<Person PersonID="p467545237">
		<Name>Damien Martyn</Name>
		<Address>240 Pammel Drive</Address>
		<DOB>1973-09-22</DOB>
	</Person>
	<Person PersonID="p477453864">
		<Name>Brett Lee</Name>
		<Address>340 Pammel Drive</Address>
		<DOB>1974-10-23</DOB>
	</Person>
	<Person PersonID="p483223789">
		<Name>Jan Harvey</Name>
		<Address>2430 South Dakota</Address>
		<DOB>1975-11-24</DOB>
	</Person>
	<Person PersonID="p483727101">
		<Name>Jim Slater</Name>
		<Address>2300 Franklin Avenue</Address>
		<DOB>1976-12-25</DOB>
	</Person>
	<Person PersonID="p485619193">
		<Name>Daniel Hayden</Name>
		<Address>235 North Hyland</Address>
		<DOB>1977-01-26</DOB>
	</Person>
	<Person PersonID="p490649143">
		<Name>Naseer Hussain</Name>
		<Address>263 North Hyland</Address>
		<DOB>1978-02-27</DOB>
	</Person>
	<Person PersonID="p495490053">
		<Name>Michael Vaughan</Name>
		<Address>153 North Hyland</Address>
		<DOB>1972-03-28</DOB>
	</Person>
	<Person PersonID="p500094214">
		<Name>Bradley Hoggs</Name>
		<Address>246 Franklin Avenue</Address>
		<DOB>1972-04-29</DOB>
	</Person>
	<Person PersonID="p501674545">
		<Name>Dennis Patten</Name>
		<Address>240 Knapp Street</Address>
		<DOB>1973-05-30</DOB>
	</Person>
	<Person PersonID="p504013895">
		<Name>Philip Simmons</Name>
		<Address>1008 Cooper Hall</Address>
		<DOB>1960-11-12</DOB>
	</Person>
	<Person PersonID="p513110141">
		<Name>Augustin Logie</Name>
		<Address>230 Sheldon Avenue</Address>
		<DOB>1974-06-01</DOB>
	</Person>
	<Person PersonID="p513729696">
		<Name>Barry Pollock</Name>
		<Address>246 Osborn Drive</Address>
		<DOB>1975-07-02</DOB>
	</Person>
	<Person PersonID="p547083692">
		<Name>Neil Foster</Name>
		<Address>243 Union Drive</Address>
		<DOB>1976-08-03</DOB>
	</Person>
	<Person PersonID="p550658107">
		<Name>Neil Radford</Name>
		<Address>245 University Village</Address>
		<DOB>1977-09-04</DOB>
	</Person>
	<Person PersonID="p555010131">
		<Name>Graeme Dilly</Name>
		<Address>564 Schiletter</Address>
		<DOB>1978-10-05</DOB>
	</Person>
	<Person PersonID="p587735656">
		<Name>Wilf slack</Name>
		<Address>560 Ash Avenue</Address>
		<DOB>1972-11-06</DOB>
	</Person>
	<Person PersonID="p590987789">
		<Name>Alex Tudor</Name>
		<Address>44 Stanton Drive</Address>
		<DOB>1973-12-07</DOB>
	</Person>
	<Person PersonID="p601496044">
		<Name>Craig White</Name>
		<Address>340 Duff Avenue</Address>
		<DOB>1974-01-08</DOB>
	</Person>
	<Person PersonID="p616740646">
		<Name>Derek Crooks</Name>
		<Address>1200 28th Street</Address>
		<DOB>1975-02-09</DOB>
	</Person>
	<Person PersonID="p644488789">
		<Name>Dave Whatmore</Name>
