=== henesy/cs363/proj5/CyDIW_Root_bin_(2015-08-24)/CyDIW_Root_bin_(2015-08-24)/ComS363/Demos/Datasets/Emp.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2011 (http://www.altova.com) by Xinyuan Zhao (Iowa State University) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Emps" type="EmpsType"/>
	<xs:complexType name="EmpsType">
		<xs:sequence maxOccurs="unbounded">
			<xs:element name="Entry" type="EntryType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="EntryType">
		<xs:sequence>
			<xs:element name="Name" type="xs:string"/>
			<xs:element name="DName" type="xs:string"/>
			<xs:element name="Salary" type="xs:double"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== henesy/cs363/proj5/CyDIW_Root_bin_(2015-08-24)/CyDIW_Root_bin_(2015-08-24)/ComS363/Demos/Datasets/Emp.xml
<Emps xsi:noNamespaceSchemaLocation="Emp.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <Entry>
      <Name>Hari</Name>
      <DName>Credit</DName>
      <Salary>55000</Salary>
    </Entry>
    <Entry>
      <Name>John</Name>
      <DName>Toys</DName>
      <Salary>50000</Salary>
    </Entry>
    <Entry>
      <Name>Leu</Name>
      <DName>Shoes</DName>
      <Salary>70000</Salary>
    </Entry>
    <Entry>
      <Name>Mary</Name>
      <DName>Toys</DName>
      <Salary>60000</Salary>
    </Entry>
    <Entry>
      <Name>Superman</Name>
      <DName>Audit</DName>
      <Salary>100000</Salary>
    </Entry>
    <Entry>
      <Name>Jane</Name>
      <DName>TV</DName>
      <Salary>65000</Salary>
    </Entry>
</Emps>
