=== henesy/cs363/proj5/CyDIW_Root_bin_(2015-08-24)/CyDIW_Root_bin_(2015-08-24)/ComS363/Demos/Datasets/ISU_Course_CatalogDB.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v2004 rel. 3 U (http://www.xmlspy.com) by Rahul (Iowa State) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Coms_Catalog">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Front_Material">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Dept_Name" type="xs:string"/>
							<xs:element name="DeptURL" type="xs:anyURI"/>
							<xs:element name="ParentDept" type="xs:string"/>
							<xs:element name="DeptChair" type="xs:string"/>
							<xs:element name="FacultyList" type="FacultyListType" maxOccurs="unbounded"/>
							<xs:element name="UgradInfo" type="xs:string"/>
							<xs:element name="GradInfo" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Courses">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="UgradCourses" type="CoursesType" minOccurs="0"/>
							<xs:element name="Grad_Ugrad_Courses" type="CoursesType" minOccurs="0"/>
							<xs:element name="GradCourses" type="CoursesType" minOccurs="0"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="CListType">
		<xs:sequence>
			<xs:element name="CourseInitial"/>
			<xs:element name="CourseNumber">
				<xs:simpleType>
					<xs:restriction base="xs:positiveInteger">
						<xs:minInclusive value="1"/>
						<xs:maxInclusive value="699"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="CourseName" type="xs:string"/>
			<xs:element name="CourseListing" type="xs:string" minOccurs="0"/>
			<xs:element name="ContactHrs" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:minInclusive value="0"/>
						<xs:maxInclusive value="9"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="ContactLabHrs" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:minInclusive value="0"/>
						<xs:maxInclusive value="9"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="CreditHrs" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:length value="1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="SemOffrd" minOccurs="0">
				<xs:complexType>
					<xs:all>
						<xs:element name="F" type="xs:string" default="F" minOccurs="0"/>
						<xs:element name="S" type="xs:string" default="S" minOccurs="0"/>
						<xs:element name="SS" type="xs:string" default="SS" minOccurs="0"/>
					</xs:all>
				</xs:complexType>
			</xs:element>
			<xs:element name="Prereq" type="xs:string" minOccurs="0"/>
			<xs:element name="CourseBody" type="xs:string"/>
			<xs:element name="NMGradCredit" type="xs:string" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="CourseListingType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Courses Primarily for Undergraduate Students"/>
			<xs:enumeration value="Courses Primarily for Graduate Students, Open to Qualified Undergraduate Students"/>
			<xs:enumeration value="Courses for Graduate Students"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="CoursesType">
		<xs:sequence>
			<xs:element name="ListTitle" type="CourseListingType"/>
			<xs:element name="CList" type="CListType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="FacultyListType">
		<xs:sequence>
			<xs:element name="FacultyPosition">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute name="Title">
								<xs:simpleType>
									<xs:restriction base="xs:string"/>
								</xs:simpleType>
							</xs:attribute>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== henesy/cs363/proj3/CyDIW_Root/ComS363/Demos/Datasets/ISU_Course_CatalogDB.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v2004 rel. 3 U (http://www.xmlspy.com) by Rahul (Iowa State) -->
<!--Sample XML file generated by XMLSPY v2004 rel. 3 U (http://www.xmlspy.com)-->
<Coms_Catalog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Documents and Settings\rahul\My Documents\XML\ISU_Course_CatalogDB.xsd">
	<Front_Material>
		<Dept_Name>Computer Science</Dept_Name>
		<DeptURL>http://www.cs.iastate.edu</DeptURL>
		<ParentDept>Computer Science</ParentDept>
		<DeptChair>Carl K. Chang, Chair of Department</DeptChair>
		<FacultyList>
			<FacultyPosition Title="Professors"> Chang, Miller</FacultyPosition>
			<FacultyPosition Title="Associate Professors">Chandra, Jones, Wang</FacultyPosition>
			<FacultyPosition Title="Assistant Professors">Bansal, Liu</FacultyPosition>
		</FacultyList>
		<UgradInfo>The curriculum in Liberal Arts and Sciences leading to a bachelor of science degree with a major in computer science is designed to prepare students for positions as computer scientists with business, industry, or government, or for graduate study in computer science.</UgradInfo>
		<GradInfo>The department offers work for the degrees master of science and doctor of philosophy with a major in Computer Science. The doctor of philosophy may also be earned with computer science as a co-major with some other discipline. Additionally, the department offers minor work to students majoring in other departments.</GradInfo>
	</Front_Material>
	<Courses>
		<UgradCourses>
			<ListTitle>Courses Primarily for Undergraduate Students</ListTitle>
			<CList>
				<CourseInitial>Com S</CourseInitial>
				<CourseNumber>311</CourseNumber>
				<CourseName>Design and Analysis of Algorithms</CourseName>
				<ContactHrs>3</ContactHrs>
				<ContactLabHrs>1</ContactLabHrs>
				<CreditHrs>3</CreditHrs>
				<SemOffrd>
					<F>F</F>
					<S>S</S>
				</SemOffrd>
				<Prereq>228, Math 166, Engl 104, and either 330 or Cpr E 310</Prereq>
				<CourseBody>Basic techniques for design and analysis of efficient algorithms. Credit may not be applied toward graduation for both 311 and 381</CourseBody>
				<NMGradCredit>Nonmajor graduate credit</NMGradCredit>
			</CList>
			<CList>
				<CourseInitial>Com S</CourseInitial>
				<CourseNumber>425</CourseNumber>
				<CourseName>High Performance Computing for Scientific and Engineering Applications</CourseName>
				<CourseListing>Same as Cpr E 425</CourseListing>
				<ContactHrs>3</ContactHrs>
				<ContactLabHrs>3</ContactLabHrs>
				<CreditHrs>3</CreditHrs>
				<SemOffrd>
					<F>F</F>
					<S>S</S>
					<SS>SS</SS>
				</SemOffrd>
				<Prereq> 311, 330, Engl 105</Prereq>
				<CourseBody>Introduction to high performance computing</CourseBody>
				<NMGradCredit>Nonmajor graduate credit</NMGradCredit>
			</CList>
			<CList>
				<CourseInitial>Com S</CourseInitial>
				<CourseNumber>461</CourseNumber>
				<CourseName>Database Systems Concepts and Internals</CourseName>
				<ContactHrs>3</ContactHrs>
				<ContactLabHrs>3</ContactLabHrs>
				<CreditHrs>3</CreditHrs>
				<SemOffrd>
					<F>F</F>
					<SS>SS</SS>
				</SemOffrd>
				<Prereq>311, Engl 105</Prereq>
				<CourseBody>Data models</CourseBody>
				<NMGradCredit>Nonmajor graduate credit</NMGradCredit>
			</CList>
			<CList>
				<CourseInitial>Com S</CourseInitial>
				<CourseNumber>471</CourseNumber>
				<CourseName>Computational Linear Algebra and Fixed Point Iteration</CourseName>
				<CourseListing>Same as Math 471</CourseListing>
				<CourseBody>See Mathematics</CourseBody>
				<NMGradCredit>Nonmajor Graduate Credit</NMGradCredit>
			</CList>
		</UgradCourses>
		<Grad_Ugrad_Courses>
			<ListTitle>Courses Primarily for Graduate Students</ListTitle>
			<CList>
				<CourseInitial>Com S</CourseInitial>
				<CourseNumber>511</CourseNumber>
				<CourseName>Design and Analysis of Algorithms</CourseName>
				<CourseListing>Same as Cpr E 511.</CourseListing>
				<ContactHrs>3</ContactHrs>
				<ContactLabHrs>0</ContactLabHrs>
				<CreditHrs>3</CreditHrs>
				<SemOffrd>
					<F>F</F>
				</SemOffrd>
				<Prereq>311</Prereq>
				<CourseBody>A study of basic algorithm design and analysis techniques. NP-completeness and approximation algorithms.</CourseBody>
			</CList>
			<CList>
				<CourseInitial>Com S</CourseInitial>
				<CourseNumber>540</CourseNumber>
				<CourseName>Principles and Practice of Compiling</CourseName>
				<CourseListing>Dual-listed with 440, same as Cpr E 540.</CourseListing>
				<ContactHrs>3</ContactHrs>
				<ContactLabHrs>1</ContactLabHrs>
				<CreditHrs>3</CreditHrs>
				<SemOffrd>
					<S>S</S>
				</SemOffrd>
				<Prereq>331, 342, Engl 105, Sp Cm 212</Prereq>
				<CourseBody>Theory of compiling and implementation issues of programming languages. Programming projects leading to the construction of a compiler. Written reports</CourseBody>
			</CList>
		</Grad_Ugrad_Courses>
		<GradCourses>
			<ListTitle>Courses for Graduate Students</ListTitle>
			<CList>
				<CourseInitial>Com S</CourseInitial>
				<CourseNumber>611</CourseNumber>
				<CourseName>Advanced Topics in Analysis of Algorithms</CourseName>
				<ContactHrs>3</ContactHrs>
				<ContactLabHrs>0</ContactLabHrs>
				<CreditHrs>3</CreditHrs>
				<SemOffrd>
					<S>Alt. S</S>
				</SemOffrd>
				<Prereq>511, 531</Prereq>
				<CourseBody>Advanced algorithm analysis and design techniques. Graph algorithms, algebraic algorithms, NP-completeness, probabilistic and parallel algorithms, intractable problems</CourseBody>
			</CList>
		</GradCourses>
	</Courses>
</Coms_Catalog>
