=== henesy/cs363/proj3/CyDIW_Root/ComS363/Demos/Datasets/PersonnelOODB_Ext.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2013 sp1 (x64) (http://www.altova.com) by SKG (Iowa State University) -->
<!-- edited with XMLSPY v5 rel. 3 U (http://www.xmlspy.com) by Shashi K Gadia (Iowa State University, Computer Science) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="PersonnelDB">
		<xs:annotation>
			<xs:documentation>Personnel Object-Oriented Scheme</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Person" type="PersonType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="Emp" type="EmpType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="Dept" type="DeptType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="Manager" type="ManagerType" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="PersonScalarType">
		<xs:sequence>
			<xs:element name="Name" type="xs:string"/>
			<xs:element name="DOB" type="xs:date"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PersonType">
		<xs:complexContent>
			<xs:extension base="PersonScalarType">
				<xs:attribute name="PersonID" type="xs:ID" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="EmpScalarType">
		<xs:complexContent>
			<xs:extension base="PersonScalarType">
				<xs:sequence>
					<xs:element name="Salary" type="xs:int"/>
					<xs:element name="WorksIn">
						<xs:complexType>
							<xs:attribute name="oType" type="xs:string" use="required" fixed="DeptType"/>
							<xs:attribute name="oID" type="xs:IDREFS" use="required"/>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="EmpType">
		<xs:complexContent>
			<xs:extension base="PersonScalarType">
				<xs:sequence>
					<xs:element name="Salary" type="xs:int"/>
					<xs:element name="WorksIn">
						<xs:complexType>
							<xs:attribute name="oType" type="xs:string" use="required" fixed="DeptType"/>
							<xs:attribute name="oID" type="xs:IDREFS" use="required"/>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
				<xs:attribute name="EmpID" type="xs:ID" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="DeptType">
		<xs:sequence>
			<xs:element name="DName" type="xs:string"/>
			<xs:element name="ManagedBy">
				<xs:complexType>
					<xs:attribute name="oType" type="xs:string" use="required" fixed="ManagerType"/>
					<xs:attribute name="oID" type="xs:IDREF" use="required"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="DeptID" type="xs:ID" use="required"/>
	</xs:complexType>
	<xs:complexType name="ManagerScalarType">
		<xs:complexContent>
			<xs:extension base="EmpScalarType">
				<xs:sequence>
					<xs:element name="Budget" type="xs:decimal"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="ManagerType">
		<xs:complexContent>
			<xs:extension base="ManagerScalarType">
				<xs:attribute name="ManagerID" type="xs:ID" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>

=== henesy/cs363/proj3/CyDIW_Root/ComS363/Demos/Datasets/PersonnelOODB_Ext.xml
<?xml version="1.0"?>
<!-- edited with XMLSPY v5 rel. 3 U (http://www.xmlspy.com) by Shashi K Gadia (Iowa State University, Computer Science) -->
<PersonnelDB xsi:noNamespaceSchemaLocation="PersonnelOODB_Ext.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	
	<Person PersonID="Person004">
		<Name>James Robe</Name>
		<DOB>1973-02-18</DOB>
	</Person>
	<Emp EmpID="Emp003">
		<Name>Eric Martin</Name>
		<DOB>1970-04-22</DOB>
		<Salary>50000</Salary>
		<WorksIn oType="DeptType" oID="Dept001"/>
	</Emp>
	<Emp EmpID="Emp004">
		<Name>Matt Simon</Name>
		<DOB>1976-01-09</DOB>
		<Salary>45000</Salary>
		<WorksIn oType="DeptType" oID="Dept002"/>
	</Emp>
	<Emp EmpID="Emp005">
		<Name>John Doe</Name>
		<DOB>1978-11-21</DOB>
		<Salary>40000</Salary>
		<WorksIn oType="DeptType" oID="Dept001 Dept002"/>
	</Emp>
	<Dept DeptID="Dept001">
		<DName>Information Service</DName>
		<ManagedBy oType="ManagerType" oID="Manager001"/>
	</Dept>
	<Dept DeptID="Dept002">
		<DName>Sales</DName>
		<ManagedBy oType="ManagerType" oID="Manager002"/>
	</Dept>
	<Manager ManagerID="Manager001">
		<Name>Mark Allen</Name>
		<DOB>1960-05-07</DOB>
		<Salary>80000</Salary>
		<WorksIn oType="DeptType" oID="Dept001"/>
		<Budget>1000000</Budget>
	</Manager>
	<Manager ManagerID="Manager002">
		<Name>Lisa Borman</Name>
		<DOB>1954-09-12</DOB>
		<Salary>75000</Salary>
		<WorksIn oType="DeptType" oID="Dept002"/>
		<Budget>400000</Budget>
	</Manager>
</PersonnelDB>
